# Generated by Django 6.0.3 on 2026-09-02 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(default='registration', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(default='guardian123', max_length=255)),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('guardian', 'Guardian / Responder'), ('user', 'Protected User')], default='user', max_length=20)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_latitude', models.FloatField(blank=True, default=17.385, null=True)),
                ('last_longitude', models.FloatField(blank=True, default=78.4867, null=True)),
                ('last_address', models.CharField(blank=True, default='Hyderabad, Telangana', max_length=255)),
                ('battery_level', models.IntegerField(default=85)),
                ('fcm_token', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=30)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='guardian_api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('relationship', models.CharField(default='Family', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='guardian_api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, default='Live Location', max_length=255)),
                ('trigger_source', models.CharField(choices=[('button', 'SOS Button'), ('shake', 'Shake Gesture'), ('voice', 'Voice Keyword'), ('timer', 'Safety Timer Expired'), ('battery', 'Low Battery (15%) Alert'), ('safe_mode', 'Safe Mode Broadcast'), ('trip', 'Trip Off-Route Divergence')], default='button', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active Emergency'), ('dispatched', 'Guardian Dispatched'), ('resolved', 'Resolved / Safe')], default='active', max_length=20)),
                ('siren_active', models.BooleanField(default=True)),
                ('battery_level', models.IntegerField(default=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_alerts', to='guardian_api.userprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='guardian_api.userprofile')),
            ],
        ),
    ]
